### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by ShantanuDash** [AJRocks321/AJRocks321.github.io#1]
- add https
- some symbols(like the one besides programming languages) are not rendering properly.
- could improve ui a bit

Btw where is it hosted rn?

**Comment by AJRocks321** [comment]
The main site is still under development.
and will soon add https:)
it is hosted on namecheap

**Comment by ShantanuDash** [comment]
Cool man!!!

**Comment by ShantanuDash** [comment]
use this for adding dynamics @gatsbyjs
